apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mi-app-php
  name: mi-app-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app-php
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mi-app-php
    spec:
      containers:
      - image: app-php-devops:latest
        name: app-php-devops
        imagePullPolicy: Never  # ← Esta línea es crucial
        resources: {}
status: {}
